server:
  port: 8081

spring:
  application:
    name: auth-service   # tên service đăng ký trên Consul, phải trùng với gateway gọi

  cloud:
    consul:
      host: localhost    # địa chỉ Consul server
      port: 8500
      discovery:
        register: true   # đăng ký service lên Consul
        enabled: true
        prefer-ip-address: true  # dùng IP thay vì hostname (nên dùng khi trong Docker hoặc mạng LAN)
  datasource:
    url: jdbc:postgresql://localhost:5432/authen_user
    username: postgres
    password: Ch@/12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password:
      expired-time: 60  # minutes
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuquocchung@gmail.com
    password: ddksvamtucophvxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:1058553511851-5nrg1p9brkjk85vb3o8hl50gt4vcaqp3.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8081/login/oauth2/code/google}
            scope:
               - profile
               - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
    default-encoding: UTF-8
jwt:
  private-key-path: classpath:key/private.pem
  public-key-path: classpath:key/public.pem
  expiration: 3600000



