<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.proshop</groupId>
  <artifactId>proshop-backend</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <modules>
    <module>auth-lib</module>
    <module>exception-lib</module>
    <module>auth-service</module>
    <module>file-service</module>
    <module>review-service</module>
    <module>sale-service</module>
    <module>gateway-service/gateway-service</module>
    <module>order-service/order-service</module>
    <module>product-service/product-service</module>
    <module>ai-service/ai-service</module>
    <module>flyway-migration-service</module>
  </modules>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.5</version>
    <relativePath/>
  </parent>

  <properties>
    <java.version>17</java.version>
    <spring-cloud.version>2023.0.3</spring-cloud.version>
  </properties>

</project>