server:
  port: 8082

spring:
  application:
    name: product-service   # tên service đăng ký trên Consul, phải trùng với gateway gọi

  config:
    import:
      optional:consul:
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        register: true   # đăng ký service lên Consul
        enabled: true
        prefer-ip-address: true  # dùng IP thay vì hostname (nên dùng khi trong Docker hoặc mạng LAN)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proshop_product}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO                        # mức log mặc định
    org.springframework: INFO         # log cho Spring
    org.hibernate.SQL: DEBUG          # hiển thị câu SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # hiển thị giá trị bind parameter
#  file:
#    name: logs/product-service.log     # log ra file (tùy chọn)

jwt:
  public-key-path: classpath:key/public.pem
  expiration: 3600000

# Feign Client URLs
order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

file:
  service:
    url: ${FILE_SERVICE_URL:http://localhost:8084}