server:
  port: 8082

spring:
  application:
    name: product-service   # tên service đăng ký trên Consul, phải trùng với gateway gọi

  config:
    import:
      optional:consul:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true   # đăng ký service lên Consul
        enabled: true
        prefer-ip-address: true  # dùng IP thay vì hostname (nên dùng khi trong Docker hoặc mạng LAN)
  datasource:
    url: jdbc:postgresql://localhost:5432/proshop_product
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO                        # mức log mặc định
    org.springframework: INFO         # log cho Spring
    org.hibernate.SQL: DEBUG          # hiển thị câu SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # hiển thị giá trị bind parameter
#  file:
#    name: logs/product-service.log     # log ra file (tùy chọn)

jwt:
  public-key-path: classpath:key/public.pem
  expiration: 3600000